services:
   # spr: sender + processor + receiver
   spr-zookeeper:
      container_name: spr-zookeeper
      image: wurstmeister/zookeeper
      ports:
      - "2181:2181"
      restart: unless-stopped
      environment:
         KAFKA_ADVERTISED_HOST_NAME: spr-zookeeper
   spr-kafka:
      container_name: spr-kafka
      image: wurstmeister/kafka
      ports:
      - "9092:9092"
      restart: unless-stopped
      environment:
         KAFKA_ADVERTISED_HOST_NAME: spr-kafka
         KAFKA_ADVERTISED_PORT: 9092
         KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://spr-kafka:9092"
         KAFKA_ZOOKEEPER_CONNECT: spr-zookeeper:2181
      depends_on:
      - spr-zookeeper
   spr-sender:
      container_name: spr-sender
      image: eeengcs/study05_kafka-sender:1.0.0-SNAPSHOT
      restart: unless-stopped
      depends_on:
      - spr-kafka
   spr-processor:
      container_name: spr-processor
      image: eeengcs/study05_kafka-processor:1.0.0-SNAPSHOT
      restart: unless-stopped
      depends_on:
      - spr-kafka
   spr-receiver:
      container_name: spr-receiver
      image: eeengcs/study05_kafka-receiver:1.0.0-SNAPSHOT
      restart: unless-stopped
      depends_on:
      - spr-kafka