FROM maven AS MAVEN_TOOL
COPY pom.xml /tmp/
COPY src /tmp/src/
WORKDIR /tmp/
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21
COPY --from=MAVEN_TOOL /tmp/target/Study05_kafka-receiver-1.0.0-SNAPSHOT.jar application.jar
ENTRYPOINT ["java","-Dspring.cloud.stream.kafka.binder.brokers=spr-kafka","-jar","application.jar"]